### ISSUE TITLE
Vids 

### ISSUE THREAD

**Issue by danhearn** [danhearn/transforming-collections#19]
Hey @lukeplowden if you have time could you look into this please - no worries if not just lmk!

Erika has sent me some videos to test about 1 min 30 seconds in length. She gave me .mp4 and .mov of the same video to test. .mp4 is 130MB .mov is 100MB. I had previously only been testing with 20 second videos and I wasn't expecting longer.

Maybe this is because I changed to pathlib? but I'm pretty sure I tested it with a shorter video and it was fine. 

**Here is the terminal error**

Loading visuals...
Visuals loaded.
Error in Media Player's run method: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glTexSubImage2D,
	pyArgs = (
		GL_TEXTURE_2D,
		0,
		0,
		0,
		1080,
		1920,
		GL_RGBA,
		GL_UNSIGNED_BYTE,
		None,
	),
	cArgs = (
		GL_TEXTURE_2D,
		0,
		0,
		0,
		1080,
		1920,
		GL_RGBA,
		GL_UNSIGNED_BYTE,
		None,
	),
	cArguments = (
		GL_TEXTURE_2D,
		0,
		0,
		0,
		1080,
		1920,
		GL_RGBA,
		GL_UNSIGNED_BYTE,
		None,
	)
)
Window terminated.

**Comment by lukeplowden** [comment]
Yeah, please send me the videos somewhere, I'm pretty sure it's because of the colour format of the videos.

**Comment by danhearn** [comment]
ok, coming in hot.

**Comment by danhearn** [comment]
forwarded to your outlook 👍

**Comment by lukeplowden** [comment]
I've hopefully fixed the issue in the attached PR :100:
